<html>

<head>
  <title><?=isset($title) ? $title : 'bashupload / upload files from command line'?></title>
  
	<link rel="stylesheet" href="<?=BASE_WEB?>/styles.css?<?=STATIC_VERSION?>">
	<script src="<?=BASE_WEB?>/script.js?<?=STATIC_VERSION?>"></script>
	
	<?php if ( WEB ) { ?>
  	<link rel="icon" href="/favicon.ico">
  	<meta name="description" content="<?=isset($description) ? $description : 'Upload files from command line to cloud and then download to desktop or server'?>">
  	<meta name="keywords" content="Upload from command line, upload using bash, upload file to server, download file from server">
  	<meta name="author" content="zeroapps.dev">
	<?php } ?>
	
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
	<div id="content">
		<header>
			<h1>Scuti's bashupload</h1>
			<p>
				Upload files directly from the command line for easily sharing. <?=file_upload_max_size()?> max.
				<br>
				Files are stored for <?=EXPIRE_DAYS?> days<?=MAX_DOWNLOADS > 1 ? '' : ' and can be downloaded only once' ?>.
			</p>
		</header>

		<?php include __DIR__ . "/{$action}.phtml"; ?>
	</div>

	<footer>
        <img src="/bashupload/assets/img/scuti-logo-small.jpg" alt="Scuti Vietnam">
        <br>
        Forked from <a href="https://github.com/denfromio/bashupload" target="_blank">bashupload</a>
        by <a target="_blank" href="http://scuti.asia">Scuti</a>.
	</footer>
	
</body>
</html>