<?php

# Output streamed if was fed

if (isset($error) && $error) {
	echo "\n";
	echo 'Error: ';
	echo $error . "\n\n";
}

if (isset($uploads) && $uploads) {
	echo "\n";
	echo '=========================';
	echo "\n\n";

	$total = 0;
	foreach ($uploads as $file) {
        $total += $file['size'];
    }

	$countUploads = count($uploads);
    $countBytes = number_format($total, 0, '.', ' ');

	echo "Uploaded ($countUploads) files. [$countBytes bytes]\n\n";

	foreach ($uploads as $file) {
		$url = $_SERVER['REQUEST_SCHEME'] . '://' . HOST . '/bashupload/files/' . $file['id'] . '/' . $file['name'];
		echo "Download using: wget {$url}" . "\n\n";
	}
	
	echo '=========================';
	echo "\n\n";
}