<?php

# Output streamed if was fed

if (isset($error) && $error) {
	echo "\n";
	echo 'Error: ';
	echo $error . "\n\n";
}

if (isset($uploads) && $uploads) {
	echo "\n";
	echo '=========================';
	echo "\n\n";

	$total = 0;
	foreach ($uploads as $file) {
        $total += $file['size'];
    }

	echo 'Uploaded '
        . count($uploads)
        . ' file, '
        . number_format($total, 0, '.', ' ')
        . ' bytes'
        . "\n\n";

	foreach ($uploads as $file) {
		$url = $_SERVER['REQUEST_SCHEME'] . '://' . HOST . '/bashupload/files' . $file['id'] . '/' . $file['name'];
		echo "wget {$url}" . "\n\n";
	}
	
	echo '=========================';
	echo "\n\n";
}